### ISSUE TITLE
Trying to mine ZEN -> unsuccessful

### ISSUE THREAD

**Issue by slazarov** [Optiminer/OptiminerEquihash#12]
I am trying to mine ZEN on eu.zenmine.pro with GTX 1070 with latest prop drivers 384.98.
The rig has 8 GPUS, running on Ubuntu Server 16.04.03
I get the following results:

- equihash200_9: > Found no matching devices! (for obvious reasons)
- equihash192_7: > low hashrate
- equihash96_5: > low hashrate

**Comment by Optiminer** [comment]
Zen uses the equihash200_9 algorithm which is currently not supported by optiminer on Nvidia cards. Sorry.
