### ISSUE TITLE
CL_DEVICE_NOT_FOUND Debian 9.0 Stretch AMD HAWAII

### ISSUE THREAD

**Issue by hzlbrmft** [Optiminer/OptiminerEquihash#13]
Using Optiminer/Equihash 2.0.0 on a Debian 9.0 System with [AMD/ATI] Hawaii PRO [Radeon R9 290/390] leads to [error] OpenCL error: Failed to read bin/Unknown_Equihash96_5-base.bin (CL_DEVICE_NOT_FOUND)
I am not sure if this is an issue or due to a missconfiguration of my system.
More info see attached file.
[optimine_foo.txt](https://github.com/Optiminer/OptiminerEquihash/files/1502966/optimine_foo.txt)

**Comment by Optiminer** [comment]
You need to start the miner from the directory where the binary is in.

**Comment by Optiminer** [comment]
Looks like you use the amdgpu driver which does not work well for mining. I have been experimenting with it for some days. It's just broken.

The R9 290/390 are supported by the fgrlx driver, so I recommend to use that. Alternatively it should also work with the amdgpu-pro driver.

**Comment by hzlbrmft** [comment]
Thanks for the response.
For Info: fgrlx is not Part of Debian 9 (Stretch). I will check for amdgpu-pro driver and will give feedback.
This is in fact not an optiminer issue, but it seems hardly possible to use it on Debian 9.

**Comment by Optiminer** [comment]
Yes, unfortunately the driver situation for AMD is rather bad with never distributions. Several distributions fully rely on amdgpu but I have not found it working well at all. It is so buggy that I cannot support it with optiminer at the moment.

**Comment by hzlbrmft** [comment]
Switched to Ubuntu 16.04, tried recommended amdgpu-pro 16.40.5. Did not work. Had to take AMDGPU-Pro Driver 17.40. New Error: AMD HSA Code Object loading failed.
Giving up.
