### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by savskii** [Optiminer/OptiminerEquihash#14]
Hello, I am getting this error every 10 minutes on all my rigs, which stops the mining giving only error as "Killed" dmesg shows the below error:

[49048.103461] Out of memory: Kill process 3024 (optiminer-equih) score 298 or sacrifice child
[49048.103463] Killed process 3024 (optiminer-equih) total-vm:88813356kB, anon-rss:103296kB, file-rss:2296504kB

I have used "watch -n 5 free -m" and see it uses all 4gbs then crashes miner. Is there any fix? or work around apart from upgrading memory lol

I have:
Ubuntu server 14.04 
Dual core Intel Celeron CPU G3930 - cache: 2MB - 2.9MHz
4GB Kingston Memory
120GB SSD 

Thanks

**Comment by schnaps1981** [comment]
same problem!

I have:
Ubuntu **desktop** 16.04
Dual core Intel Celeron CPU G3930 - cache: 2MB - 2.9MHz
**8**GB RAM
120GB SSD

**Comment by Optiminer** [comment]
Should be fixed in 2.1.0. Please reopen if not.
