### ISSUE TITLE
SM version specified by .target is higher than default SM version assumed

### ISSUE THREAD

**Issue by suiyidajiangyou** [Optiminer/OptiminerEquihash#18]
I can't run the "optiminer-equihash" and that's the error
./optiminer-equihash: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./optiminer-equihash)
./optiminer-equihash: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./optiminer-equihash)
./optiminer-equihash: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./optiminer-equihash)
[2017-12-05 14:10:19.541] [info] Optiminer/Equihash 2.0.0 (C) Optiminer 2017
[2017-12-05 14:10:19.541] [info] Connecting to mnx.suprnova.cc:7076.
[2017-12-05 14:10:20.417] [info] Using generic kernel code.
[2017-12-05 14:10:20.417] [info] Autodetected '--intensity 128' for device 0.
[2017-12-05 14:10:20.418] [info] [GPU0] Device info: {"id": "0/0" "name": "GeForce GTX 960" "platform": "Nvidia" "driver": "384.90"}
[2017-12-05 14:10:20.453] [error] Build Status: -2
[2017-12-05 14:10:20.453] [error] Build Log:
ptxas fatal   : SM version specified by .target is higher than default SM version assumed

GPU: gtx960 
cuda 8.0 cudnn6

**Comment by Optiminer** [comment]
That's strange. What is the output of clinfo?

**Comment by Optiminer** [comment]
Try v2.1.0.

**Comment by gaissa** [comment]
The minimum SM version for 2.1.0 is? The oldest NVIDIA card working? Add that info please.

**Comment by Optiminer** [comment]
Minimum SM version is 32 (= compute capability 3.2). See

**Comment by antonavy** [comment]
Sorry to reanimate, but I have 980ti, it has 5.2 CC, same error. Why is that?

**Comment by Optiminer** [comment]
Are you sure you have tried with version 2.1? Please post full output of the miner.

**Comment by antonavy** [comment]
Oh, I'm sorry, I've mistaken this one with OptimizerZero. I'm yet to try this one, didn't wanna switch to linux.

**Comment by tuerkasten** [comment]
any chance to lower the minimum SM Version to support GTX550 TI. I know it's kinda pointless mining with that old card but I got access to free electricity
