### ISSUE TITLE
Unsupported .version 6.0; current version is 5.0

### ISSUE THREAD

**Issue by mikebzh44** [Optiminer/OptiminerEquihash#19]
Hello.

I'm trying to run Optiminer-Equihash 2.1.0 on my rig but I have this error mesage :

https://i.imgur.com/NZCSSWZ.png

Optiminer-Equihash-2.0.0 work well on my rig (4 GTX 1060 6 Gb).

Could you tell me what I need to upgrade ?

Thanks.

**Comment by Optiminer** [comment]
You need to update the version of CUDA installed on your system.

**Comment by mikebzh44** [comment]
SO need to upgrade to CUDA 9 ?

**Comment by Optiminer** [comment]
Yes, version 6 ISA is only supported with cuda 9. I'll try to lower the required version for the next release.

**Comment by Optiminer** [comment]
v2.1.1 should also work with older cuda versions.
