### ISSUE TITLE
Not all SM versions supported

### ISSUE THREAD

**Issue by adrienneoui** [Optiminer/OptiminerEquihash#2]
ptxas fatal   : SM version specified by .target is higher than default SM version assumed

Ubuntu 16.04

Multiple people had same problem and looked for a solution in your thread too.

**Comment by Optiminer** [comment]
2.0 only supports SM 61 or higher.

**Comment by adrienneoui** [comment]
I don't what SM stands for. Is there any way for me to upgrade or install the 61 or higher version?

**Comment by Optiminer** [comment]
No, the SM depends on the hardware. See here http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by adrienneoui** [comment]
OK, now everything makes sense.

Would it be possible for you lower the SM?

**Comment by Optiminer** [comment]
Yes, expected for next release.

**Comment by adrienneoui** [comment]
Awesome, thank you so much.

**Comment by adrienneoui** [comment]
Any possible date for new release? Looking forward to it.

**Comment by aseem00r** [comment]
I second. 
Has the attempt to bring it been successfu yetl?

**Comment by Optiminer** [comment]
Version 2.1. lowers the minimum SM target to 32. Could not try myself though.

**Comment by adrienneoui** [comment]
First of all, thank you for the effort and hard work.

Just tested, it works perfectly fine.
