### ISSUE TITLE
Error: Compilation from LLVMIR binary to IL text failed!

### ISSUE THREAD

**Issue by bellodox** [Optiminer/OptiminerEquihash#22]
Frontend phase failed compilation.
Error: Compilation from LLVMIR binary to IL text failed!
is still seen in the 2.1v at Ubuntu 14.04 2GB RAM and four r9 380 4GB for MNX mining w/ 16 swap file

**Comment by Optiminer** [comment]
Use ubuntu 16.04 with amdgpu-pro.

**Comment by wex123** [comment]
Hi, something always appeared to my screen on my computer says" Error: Compilation from LLVMIR binary to IL text failed! " I've installed dev c ++ but not sure how this fix, I have tried to delete already the dev c++ but still nothing works. Can someone help me to fix this?

**Comment by Optiminer** [comment]
If you get this error you do not use the amdgpu-pro graphic driver.
