### ISSUE TITLE
Waiting for work from pool

### ISSUE THREAD

**Issue by backendmaster** [Optiminer/OptiminerEquihash#24]
Hello, this is same for 1.2 and sometimes for 2.0 
It says something like waiting for work from pool and stays that way.
It happens when software happen to miss the authenticate in the pool and is marked as "unauthorized".

What happens is that for the pool this is not valid client, and for the worker - there is not job from the pool and he waits...
Can you do it when it waits for 30 sec to restart the process? It is obvious new work is not going to arrive.

**Comment by Optiminer** [comment]
Please provide a log. Does this happen with all pools or just some? I wonder if this is a protocol error of the server or of the miner.

The miner already reconnects when it does not get any new message from the server for 5 minutes. I think in the stratum protocol there is no specific time interval in which the server is supposed to send new work. Therefore, the 5 minutes is relatively conservative.

**Comment by backendmaster** [comment]
```
[2017-11-28 09:16:39.241] [info] Connecting to zer.forgetop.com:2052.
[2017-11-28 09:16:39.244] [info] GPU1 Waiting for work from pool.
[2017-11-28 09:16:39.264] [info] GPU3 Waiting for work from pool.
[2017-11-28 09:16:39.272] [info] GPU5 Waiting for work from pool.
[2017-11-28 09:16:39.302] [info] GPU2 Waiting for work from pool.
[2017-11-28 09:16:39.316] [info] Connecting to zer.forgetop.com:2052.
```
The reconnect in this case happens only after I wrote a bash script to kill the miner when met "waiting for work". In regular cases it freezes this way forever.

> I wonder if this is a protocol error of the server or of the miner.
This might be nobodies fault. Like PM2 reboot to free up memory or anything else. The thing is - it will be good if this case is covered on miner level.

As long as i know this happens with all pools, more often on some then the others (it happens mostly with windows miners, but not only).  

>  I think in the stratum protocol there is no specific time interval in which the server is supposed to send new work. 

```javascript
function StartStratumServer(finishedCallback) {
        _this.stratumServer = new stratum.Server(options, authorizeFn);

        _this.stratumServer.on('started', function () {
            options.initStats.stratumPorts = Object.keys(options.ports);
            _this.stratumServer.broadcastMiningJobs(_this.jobManager.currentJob.getJobParams());
            finishedCallback();

        }).on('broadcastTimeout', function () {
            emitLog('No new blocks for ' + options.jobRebroadcastTimeout + ' seconds - updating transactions & rebroadcasting work');
```


This is partially true. In most cases this is set up to 55 sec. Some mining programs reconnect on 1 min inactivity so if you do it in 1 min 10 sec this would be great.

One more thing - is there a chance windows users to get upgraded version of the miner to cover this problem? They suffer the most and they are not so little as you might think.

**Comment by tomose** [comment]
This is an instance where having an option like -FS exit similar to ethminer would be nice. Then for those of us who run this miner in a batch with others to mine the most profitable coin can auto switch. As of yet, I have not found a way to auto switch without a third party script running and may hop off this miner and find another for equihash.

**Comment by backendmaster** [comment]
Hello, any update on this one? Sorry to bother but this morning i find out one of my rigs frozen again..

**Comment by backendmaster** [comment]
It is that every one on the chain is loosing, me, the pool, ultimately optiminer as well :1234:

**Comment by Optiminer** [comment]
I cannot reproduce this problem. In your case the pool is up and running or not? If the pool is not reachable the miner of course cannot connect and get work from it.. Can you post a full log?

**Comment by backendmaster** [comment]
For sure the pool i up and running. I deleted the log last time, I will have to wait until it happens again. I am not sure do i need to mention this but this happens in zero network.
There was no any interruptions on the pool it self either.
I just speculate, it might be that network went down for a bit or who knows..
But again the thing is that if the miner did not get work for some period of time it should try to reconnect...

**Comment by Labr0** [comment]
I got this problems aswell since yesterday with the Optiminer Zero (1.1 and 1.2), got no work at all, All Cards are waiting for work (on every pool, mine included) other miners work like before. (its connected aswell)

**Comment by backendmaster** [comment]
It does not happen often and i guess this is why you have problems getting it.
