### ISSUE TITLE
AMD HSA code object loading failed ERROR

### ISSUE THREAD

**Issue by 13umble13ee** [Optiminer/OptiminerEquihash#29]
Hello,

So as it says in title, i have problem with newer versions of optiminer (2.0; 2.1; 2.1.1).

1. I am using Linux Ubuntu 16.4 server

2. My graphic card is Amd RX 470 (Didn't try to reproduce it on other cards)

3. Driver is amdgpu-pro 16.40.5

4.  I am using equihash96_5 algo

Want to know what am i doing wrong. Thanks....

![20171212_081634](https://user-images.githubusercontent.com/34790000/34318934-f457c026-e7d3-11e7-826f-59de9e3c4a04.jpg)

**Comment by Optiminer** [comment]
Please try the version 2.1.2.

**Comment by bdjakovic** [comment]
Thanks, 
Problem is solved when i updated optiminer to 2.1.2

Sorry for the late answer.
