### ISSUE TITLE
libOpenCL.so.1 cannot open object

### ISSUE THREAD

**Issue by anddmx** [Optiminer/OptiminerEquihash#30]
Is this correct for the symlink? I am still getting OpenCL error.

`sudo ln -s /opt/AMDAPPSDK-3.0/include /usr/lib/libOpenCL.so.1`

`[2017-12-29 00:43:28.811] [default] [error] OpenCL error: Failed to list OpenCL platforms! (Unknown OpenCL error -1001)`

I have AMD APP SDK install in this folder "/opt/AMDAPPSDK-3.0/include".

**Comment by Optiminer** [comment]
You need to link the OpenCL library, not the directory.

**Comment by anddmx** [comment]
Do you have example?

**Comment by Optiminer** [comment]
No. Google how to properly install opencl for your OS.
