### ISSUE TITLE
Found device with 32-bit addressing. You need to set the environment variable 'GPU_FORCE_64BIT_PTR=1'!

### ISSUE THREAD

**Issue by aseem00r** [Optiminer/OptiminerEquihash#5]
OUTPUT

pc@pc-pc:~/Downloads/optiminer-equihash-2.0.0/optiminer-equihash$ ./optiminer-equihash --benchmark 60 -a equihash96_5 -c 0 --pci-mode 1
[2017-11-16 15:09:58.109] [info] Optiminer/Equihash 2.0.0 (C) Optiminer 2017
[2017-11-16 15:09:58.111] [error] Found device with 32-bit addressing. You need to set the environment variable 'GPU_FORCE_64BIT_PTR=1'!

I get this error every time I try to start the miner.

list-devices output

[2017-11-16 15:16:54.063] [info] Optiminer/Equihash 2.0.0 (C) Optiminer 2017
Platform (-c) 0, Device (-d) 0:
  Platform Vendor: Nvidia
  Device Name: GeForce GTX 750 Ti
  Driver Version: 340.104
  Address bits: 32
  Available memory: 2146762752

How do I change the Address bits? Or is it trying to mine using OpenCL instead of CUDA?

**Comment by Optiminer** [comment]
As the message says, set GPU_FORCE_64BIT_PTR=1 before starting the miner, e.g. through
$ GPU_FORCE_64BIT_PTR=1 ./optiminer-equihash --benchmark 60 -a equihash96_5 -c 0 --pci-mode 1

Or just use the provided mine_mnx.sh script. You can pass additional args to the script as well, e.g.,
$ sh mine_mnx.sh --benchmark 60 -a equihash96_5 -c 0 --pci-mode 1
