### ISSUE TITLE
Optiminer 2.0.0

### ISSUE THREAD

**Issue by DrZeck** [Optiminer/OptiminerEquihash#6]
So far works perfect, i have decide to post good news also not only issues :)

so here is config:

Ubuntu > Server 16.04.3
Kernel > 4.10.0-38-generic x86_64
Driver > amdgpu-pro-17.40-483984
Optiminer ver: 2.0.0

**Comment by jonabasque** [comment]
hi, it is possible to mine with the 500 series ?

thanks

**Comment by Lordpit** [comment]
17.40 is fine for rx470/480 and 570, running here.

**Comment by botdruff** [comment]
running a RX 580 with 17.40 here

**Comment by DrZeck** [comment]
AMD works without any issues, NVIDIA not so fine, i am running nv cards also but need VERYYY often restart, just 144 times per day :))) , i had issues also with latest driver filling ram like crazy then fail, that problem is gone with 375, but now have problems with filling buffer and also fail, cpu usage on G1840 & G3900 is 100% always same things happen, tested on 8x1070, 5x1060 (3GB) and 6x1070 ... but overall can work somehow, cron is miracle :)

Cheers,

**Comment by Optiminer** [comment]
Thanks for feedback. Please try version 2.1.

**Comment by DrZeck** [comment]
Testing on 1 1060 now, works Okay, no mem problems at all, we shall se 2morow on 8x1070.

Cheers

**Comment by DrZeck** [comment]
Possible to add some table to sort json stats in browser. no big deal and we already have stats just would be nice to sort it in some table :))

Cheers #2

**Comment by DrZeck** [comment]
@ Lordpit

amd hangs are related to hardware ( extenders ) i have been killing myself 4 days to figure that out. 

very interesting things happens, everything works smooth except MNX i got it running only with blue 006C extenders but perfect results i got only with 008S white extenders ... maybe its just cables, i have noticed better results even speed with dark blue usb cables and mostly have issues with light blue cables ... or maybe i just have freaked out :) BUT white raisers works. all of that is related to MNX only.

**Comment by DrZeck** [comment]
NV works fine, 6x1070, 8x1070 is overkill but with some powerfull cpu that would also work. however 6 PCS works fine on G4400, can u tell me wich kernel u use in ur test system ?

Cheers
